name: CI/CD
run-name: ${{ github.actor }} build and test 👾
defaults:
  run:
    working-directory: '.'
on:
  push:
    branches:
      - main
      - release
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build:dev
      - run: npm test
